{
  logsForTarget: [
    {
      MessageTemplate: Sent message {OutgoingMessageType} {OutgoingMessageId}.,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        OutgoingMessage: {
          TypeTag: StartHandlerThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        OutgoingMessageId: Guid_2,
        OutgoingMessageType: StartHandlerThatThrows,
        ProcessingEndpoint: SerilogTestsStartHandlerThatThrows,
        ReplyToAddress: SerilogTestsStartHandlerThatThrows,
        SourceContext: StartHandlerThatThrows,
        UnicastRoutes: {
          Elements: [
            SerilogTestsStartHandlerThatThrows
          ]
        }
      }
    }
  ],
  logsWithExceptions: [
    {
      MessageTemplate: Immediate Retry is going to retry message '00000000-0000-0000-0000-000000000001' because of an exception:,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "Message type": StartHandlerThatThrows,
                "Handler type": TheHandlerThatThrows,
                "Handler start time": DateTimeOffset_1,
                "Handler failure time": DateTimeOffset_2,
                "Handler canceled": false,
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_4,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": Exception of type 'System.Exception' was thrown.,
            "Source": Tests,
            "TargetSite": Void MoveNext()
          }
        },
        HandlerFailureTime: DateTimeOffset_3,
        HandlerStartTime: DateTimeOffset_4,
        HandlerType: TheHandlerThatThrows,
        IncomingMessage: {
          TypeTag: StartHandlerThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingMessageType: StartHandlerThatThrows,
        IncomingTransportMessageId: Guid_4,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartHandlerThatThrows,
        ReplyToAddress: SerilogTestsStartHandlerThatThrows,
        SourceContext: NServiceBus.ImmediateRetry,
        TimeSent: DateTimeOffset_5
      }
    },
    {
      MessageTemplate: Delayed Retry will reschedule message '00000000-0000-0000-0000-000000000001' after a delay of 00:00:00.0010000 because of an exception:,
      Level: Warning,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "Message type": StartHandlerThatThrows,
                "Handler type": TheHandlerThatThrows,
                "Handler start time": DateTimeOffset_6,
                "Handler failure time": DateTimeOffset_7,
                "Handler canceled": false,
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_4,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": Exception of type 'System.Exception' was thrown.,
            "Source": Tests,
            "TargetSite": Void MoveNext()
          }
        },
        HandlerFailureTime: DateTimeOffset_8,
        HandlerStartTime: DateTimeOffset_9,
        HandlerType: TheHandlerThatThrows,
        IncomingMessage: {
          TypeTag: StartHandlerThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingMessageType: StartHandlerThatThrows,
        IncomingTransportMessageId: Guid_4,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartHandlerThatThrows,
        ReplyToAddress: SerilogTestsStartHandlerThatThrows,
        SourceContext: NServiceBus.DelayedRetry,
        TimeSent: DateTimeOffset_5
      }
    },
    {
      MessageTemplate: Immediate Retry is going to retry message '00000000-0000-0000-0000-000000000001' because of an exception:,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        DeliverAt: DateTimeOffset_10,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "Message type": StartHandlerThatThrows,
                "Handler type": TheHandlerThatThrows,
                "Handler start time": DateTimeOffset_11,
                "Handler failure time": DateTimeOffset_12,
                "Handler canceled": false,
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_5,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": Exception of type 'System.Exception' was thrown.,
            "Source": Tests,
            "TargetSite": Void MoveNext()
          }
        },
        HandlerFailureTime: DateTimeOffset_13,
        HandlerStartTime: DateTimeOffset_14,
        HandlerType: TheHandlerThatThrows,
        IncomingMessage: {
          TypeTag: StartHandlerThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingMessageType: StartHandlerThatThrows,
        IncomingTransportMessageId: Guid_5,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartHandlerThatThrows,
        ReplyToAddress: SerilogTestsStartHandlerThatThrows,
        Retries: 1,
        Retries.Timestamp: DateTimeOffset_15,
        SourceContext: NServiceBus.ImmediateRetry,
        TimeSent: DateTimeOffset_5
      }
    },
    {
      MessageTemplate: Moving message '00000000-0000-0000-0000-000000000001' to the error queue 'error' because processing failed due to an exception:,
      Level: Error,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        DeliverAt: DateTimeOffset_10,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "Message type": StartHandlerThatThrows,
                "Handler type": TheHandlerThatThrows,
                "Handler start time": DateTimeOffset_16,
                "Handler failure time": DateTimeOffset_17,
                "Handler canceled": false,
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_5,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": Exception of type 'System.Exception' was thrown.,
            "Source": Tests,
            "TargetSite": Void MoveNext()
          }
        },
        HandlerFailureTime: DateTimeOffset_18,
        HandlerStartTime: DateTimeOffset_19,
        HandlerType: TheHandlerThatThrows,
        IncomingMessage: {
          TypeTag: StartHandlerThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingMessageType: StartHandlerThatThrows,
        IncomingTransportMessageId: Guid_5,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartHandlerThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartHandlerThatThrows,
        ReplyToAddress: SerilogTestsStartHandlerThatThrows,
        Retries: 1,
        Retries.Timestamp: DateTimeOffset_15,
        SourceContext: NServiceBus.MoveToError,
        TimeSent: DateTimeOffset_5
      }
    }
  ]
}