{
  logsForTarget: [
    {
      MessageTemplate: Sent message {OutgoingMessageType} {OutgoingMessageId}.,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartBehaviorThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        OutgoingMessage: {
          TypeTag: StartBehaviorThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        OutgoingMessageId: Guid_2,
        OutgoingMessageType: StartBehaviorThatThrows,
        ProcessingEndpoint: SerilogTestsStartBehaviorThatThrows,
        ReplyToAddress: SerilogTestsStartBehaviorThatThrows,
        Route: SerilogTestsStartBehaviorThatThrows,
        SourceContext: StartBehaviorThatThrows
      }
    }
  ],
  logsWithExceptions: [
    {
      MessageTemplate: Immediate Retry is going to retry message '00000000-0000-0000-0000-000000000001' because of an exception:,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_4,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": The Exception,
            "Source": Tests,
            "TargetSite": System.Threading.Tasks.Task Invoke(NServiceBus.Pipeline.IInvokeHandlerContext, System.Func`1[System.Threading.Tasks.Task])
          }
        },
        IncomingMessage: {
          TypeTag: StartBehaviorThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_4,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartBehaviorThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartBehaviorThatThrows,
        ReplyToAddress: SerilogTestsStartBehaviorThatThrows,
        SourceContext: NServiceBus.ImmediateRetry,
        TimeSent: DateTimeOffset_1
      }
    },
    {
      MessageTemplate: Delayed Retry will reschedule message '00000000-0000-0000-0000-000000000001' after a delay of 00:00:00.0010000 because of an exception:,
      Level: Warning,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_4,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": The Exception,
            "Source": Tests,
            "TargetSite": System.Threading.Tasks.Task Invoke(NServiceBus.Pipeline.IInvokeHandlerContext, System.Func`1[System.Threading.Tasks.Task])
          }
        },
        IncomingMessage: {
          TypeTag: StartBehaviorThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_4,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartBehaviorThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartBehaviorThatThrows,
        ReplyToAddress: SerilogTestsStartBehaviorThatThrows,
        SourceContext: NServiceBus.DelayedRetry,
        TimeSent: DateTimeOffset_1
      }
    },
    {
      MessageTemplate: Immediate Retry is going to retry message '00000000-0000-0000-0000-000000000001' because of an exception:,
      Level: Information,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        DeliverAt: DateTimeOffset_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_5,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": The Exception,
            "Source": Tests,
            "TargetSite": System.Threading.Tasks.Task Invoke(NServiceBus.Pipeline.IInvokeHandlerContext, System.Func`1[System.Threading.Tasks.Task])
          }
        },
        IncomingMessage: {
          TypeTag: StartBehaviorThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_5,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartBehaviorThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartBehaviorThatThrows,
        ReplyToAddress: SerilogTestsStartBehaviorThatThrows,
        Retries: 1,
        Retries.Timestamp: DateTimeOffset_3,
        SourceContext: NServiceBus.ImmediateRetry,
        TimeSent: DateTimeOffset_1
      }
    },
    {
      MessageTemplate: Moving message '00000000-0000-0000-0000-000000000001' to the error queue 'error' because processing failed due to an exception:,
      Level: Error,
      Properties: {
        ContentType: application/json,
        ConversationId: Guid_1,
        CorrelationId: Guid_2,
        DeliverAt: DateTimeOffset_2,
        ExceptionDetail: {
          Elements: {
            "Type": System.Exception,
            "Data": {
              Elements: {
                "ExceptionLogState": {
                  TypeTag: ExceptionLogState
                },
                "Message ID": Guid_2,
                "Transport message ID": Guid_5,
                "Pipeline canceled": false
              }
            },
            "HResult": -2146233088,
            "Message": The Exception,
            "Source": Tests,
            "TargetSite": System.Threading.Tasks.Task Invoke(NServiceBus.Pipeline.IInvokeHandlerContext, System.Func`1[System.Threading.Tasks.Task])
          }
        },
        IncomingMessage: {
          TypeTag: StartBehaviorThatThrows,
          Properties: [
            {
              Property: TheProperty
            }
          ]
        },
        IncomingMessageId: Guid_2,
        IncomingTransportMessageId: Guid_5,
        MessageIntent: Send,
        OriginatingEndpoint: SerilogTestsStartBehaviorThatThrows,
        OriginatingHostId: Guid_3,
        OriginatingMachine: TheMachineName,
        ProcessingEndpoint: SerilogTestsStartBehaviorThatThrows,
        ReplyToAddress: SerilogTestsStartBehaviorThatThrows,
        Retries: 1,
        Retries.Timestamp: DateTimeOffset_3,
        SourceContext: NServiceBus.MoveToError,
        TimeSent: DateTimeOffset_1
      }
    }
  ]
}